language: objective-c
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=flake8

before_install:
    - brew update
    - brew install poppler djvulibre
    - brew outdated poppler || brew upgrade poppler
    - brew outdated djvulibre || brew upgrade djvulibre

install:
    - sudo pip install tox coveralls

script: 
    - tox -e $TOX_ENV

after_success:
    - cd tests
    - coveralls
