language: objective-c
env:
    matrix:
        - TOX_ENV=py27
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=pypy
        - TOX_ENV=pypy3
        - TOX_ENV=flake8

install:
    - ./.travis/install.sh

script: 
    - ./.travis/run.sh

after_success:
    - source ~/.venv/bin/activate
    - coveralls
